Change response time to 800 ms
edgexfoundry/blackbox-testing pull request #183
Opened 2019-03-20 07:53 UTC by cherrycl

Signed-off-by: Cherry Wang <cherry@iotechsys.com>
fix #182

2019-03-20 16:25 UTC, cloudxxx8 requested changes
please add 1 more second for support-rules-engine creation

2019-03-21 02:10 UTC, cherrycl commented
> please add 1 more second for support-rules-engine creation

@cloudxxx8 The response time of create rule has been updated.

2019-03-21 02:13 UTC, cloudxxx8 approved these changes

2019-03-21 02:13 UTC, cloudxxx8 commented
LGTM

2019-03-21 02:19 UTC, merged